apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- ../default
- ../rbac

patches:
- path: patch-manager.yaml

# cluster api + infra is essentially the same environment (kind cluster)
secretGenerator:
- files:
  - kubeconfig
  name: kubeconfig
- files:
  - cloud-config
  name: cloud-config
- files:
  - ironcore/kubeconfig
  name: ironcore-kubeconfig
